### ISSUE TITLE
Do you have any plans to implement microphone mode?

### ISSUE THREAD

**Issue by tomohiku** [Microsoft/Cognitive-Speech-STT-ServiceLibrary#1]
Thank you for your codes.
I wanna implement microphone mode,Do you have any plans to implement microphone mode?

**Comment by StefanRiedmann** [comment]
The library used in this example is meant for service implementations. For direct usage of microphones on a client, you can have a look to this one:
https://www.microsoft.com/cognitive-services/en-us/Speech-api/documentation/GetStarted/GetStartedCSharpDesktop

**Comment by tomohiku** [comment]
Thank you for replay.

**Comment by amrmahdi** [comment]
We do not plan to support a microphone mode in this SDK. You can still implement a stream functionality in such a way that you  writes microphone audio data while the SDK reads it.
