### ISSUE TITLE
Request finishes, but no result events occur

### ISSUE THREAD

**Issue by StefanRiedmann** [Microsoft/Cognitive-Speech-STT-ServiceLibrary#2]
The api key is fine, and works with the client library: 
https://www.microsoft.com/cognitive-services/en-us/Speech-api/documentation/GetStarted/GetStartedCSharpDesktop

But that client library doesnt work in Azure, where I want to deploy my service, so I would really need the service sdk.

The file I'm sending with the request is the same 'whatstheweatherlike.wav' like in the wpf example. 

Any idea how to get more debug info?

**Comment by amrmahdi** [comment]
Are you using the exact sample code and it is not working ? Do you have the trace logs emitted from the SDK?

**Comment by priyaravi20** [comment]
Closing due to no response.
