### ISSUE TITLE
No LongDictation results for certain locales

### ISSUE THREAD

**Issue by emillundh** [Microsoft/Cognitive-Speech-STT-ServiceLibrary#3]
I am trying Long Dictation mode in in Swedish and English. English works fine, Swedish does not. Results for me turn out as follows, **consistently**:
* en-US, short phrase mode: I receive results as expected. 
* en-US, long dictation mode: I receive results as expected. (A sequence of final n-best results.)
* sv-SE, short phrase mode: I receive results as expected. 
* sv-SE, long dictation mode: The program prints "No phrase response is available.", and then seems to hang indefinitely. 
I checked a few other locales. Some that do seem to work are de-DE and es-ES. Locales that do _not_ work include da-DK and fi-FI. 

I have tried several valid, wav files in Swedish as well as English, not too long (ranging from 10 seconds up to two minutes), produced by the same tools (ffmpeg).

Why can I not use sv-SE in long dictation mode?

**Comment by amrmahdi** [comment]
Hi @emillundh,

Unfortunately we don't support sv-SE in long dictation mode. The current [documentation](https://www.microsoft.com/cognitive-services/en-us/Speech-api/documentation/overview#supported-languages) does **not** list the supported locales per mode independently, we will make sure to update that.

Regarding hanging, the SDK should not hang, instead currently, we do throw a ServerException with "Internal Server Error" message. Just verified this behavior using the [sample](https://github.com/Microsoft/Cognitive-Speech-STT-ServiceLibrary/blob/master/sample/SpeechClientSample/Program.cs)  in this repo.

**Comment by emillundh** [comment]
Well, when I run the sample, after the "No phrase response is available" message all the controls are greyed out and can't be clicked... but that's a minor thing. Now at least I understand that some locales are simply not supported in long dictation mode, thank you. :)

**Comment by amrmahdi** [comment]
@emillundh  I think you are referring to a different library and different [sample](https://github.com/Microsoft/Cognitive-Speech-STT-Windows/blob/c88c83041fba6fbd5cba87505fae3eea6c3ec6ab/samples/SpeechRecognitionServiceExample/MainWindow.xaml.cs), hence the confusion. 

@jasonvomsft to address the sample issue.

**Comment by priyaravi20** [comment]
This has been fixed and sv-SE is now supported.

**Comment by emillundh** [comment]
Why, I just cloned the Windows SDK and run the sample from the master branch. 
On changing the locale from 'en-US' to 'sv-SE', I do receive Swedish text in the short phrase mode, but in the Long dictation mode, I receive only a long sequence of "No phrase response is available".
Was the Windows SDK not updated?
